# Generated by Django 4.0.2 on 2022-02-26 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bin2text', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CryptData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_text', models.TextField(max_length=320)),
                ('crypt', models.CharField(blank=True, choices=[('en', 'encode'), ('de', 'decode')], default='de', max_length=2)),
                ('crypt_date', models.DateTimeField(verbose_name='crypt date')),
                ('guess_ip', models.GenericIPAddressField()),
                ('output_text', models.TextField(max_length=320)),
            ],
            options={
                'ordering': ['crypt_date'],
            },
        ),
        migrations.DeleteModel(
            name='InputText',
        ),
    ]
