# Generated by Django 4.0.2 on 2022-02-26 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bin2text', '0002_cryptdata_delete_inputtext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptdata',
            name='crypt',
            field=models.CharField(choices=[('en', 'encode'), ('de', 'decode')], default='de', max_length=2),
        ),
    ]
